services:
  db:
    image: postgres:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      EDITOR: vim
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && yarn install && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
volumes:
  postgres_data:
  bundle_data:
  node_modules:
  redis:
